# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "microk8s"

  config.vm.blabla_cpus = 4
  config.vm.blabla_memory = 2048

  config.vm.network "forwarded_port", guest: 2375, host: 2375
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provision :shell, :path => "install_microk8s.sh"
  config.vm.provision :shell, :path => "config_microk8s.sh"
end
